# Generated by Django 2.1.7 on 2019-04-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mod_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tel',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mail',
            field=models.CharField(blank=True, max_length=64, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='url_list',
            field=models.TextField(default=1, verbose_name='监控列表'),
            preserve_default=False,
        ),
    ]
